Dev/shchawl/anynewline
dotnet/corefx pull request #41195
Opened 2019-09-19 07:05 UTC by shishirchawla

Adds a new regex option - RegexOptions.AnyNewLine, which supports '\r' (old mac), '\n' (unix), and '\r\n' (windows) as line endings for the '$' (EOL) operator.

2019-09-19 07:05 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/corefx?pullRequest=41195) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/corefx?pullRequest=41195) before we can accept your contribution.<br/><br/>:x: shishirchawla [sign now](https://cla.dotnetfoundation.org/dotnet/corefx?pullRequest=41195)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/corefx?pullRequest=41195) it.</sub>

2019-09-19 09:13 UTC, danmosemsft commented
Thanks @shishirchawla! Added @viktorhofer for review

2019-10-04 23:54 UTC, danmosemsft commented
I'm trying to parse the requested API design, @ViktorHofer can review this better.

The docs say `By default, $ matches only the end of the input string. If you specify the RegexOptions.Multiline option, it matches either the newline character (\n) or the end of the input string. It does not, however, match the carriage return/line feed character combination. To successfully match them, use the subexpression \r?$ instead of just $.`. 

It looks like this is a little misleading because the `$` is also magic in that it will not consume the newline if any. So given text `foo\n` (or `foo`) and pattern `foo$` the match will be `foo` not `foo\n`. And given `bar\nbaz\n`, `bar$` and `RegexOptions.Multiline` the match will be `bar` not `bar\n`.

My question then is does ` RegexOptions.AnyNewLine` have any effect if `RegexOptions.Multiline` isn't also passed? I assume it does because otherwise the proposal would have been to add ` RegexOptions.AnyNewLineMultiline` or something.

2019-10-04 23:59 UTC, danmosemsft commented on src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexInterpreter.cs
> +                        if (rightChars == 2 && (CharAt(Textpos()) != '\r' || CharAt(Textpos()+1) != '\n'))
Nit, spaces around `+`

2019-10-05 00:18 UTC, danmosemsft commented on src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexOptions.cs
> +        AnyNewLine              = 0x0400, // "a", Treat "$" as (?=[\r\n]|\z)
As mentioned in the issue `(?=[\r\n]|\z)` matches "any one of \r, \n, or end of input" whereas what is intended is "any one of \r, \n, \r\n, or end of input". Plus, only end of input if Multiline is not also set (?)

2019-10-05 00:24 UTC, danmosemsft commented
Is this right?

flags    |    $ is treated as         
------------- | ------------- 
neither     |   `(?=\n\z\|\z)` 
RegexOptions.Multiline     |  `(?=\r\n\z\|\r\z\|\n\z\|\z)`  
RegexOptions.Multiline \| RegexOptions.AnyNewline | `(?=\r\n\|\r\|\n)`  
RegexOptions.AnyNewline | dunno?

@jzabroski @svick

2019-10-05 00:29 UTC, danmosemsft commented on src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexOptions.cs
> +        AnyNewLine              = 0x0400, // "a", Treat "$" as (?=[\r\n]|\z)
I think it needs a more precise definition, which I'm not clear about so hopefully someone can help clarify it in discussion here.

2019-10-05 00:41 UTC, danmosemsft commented
What about the behavior of `\Z` (capital Z) -- docs say, "\Z | The match must occur at the end of the string or before \n at the end of the string.". 

seems like $ where it ignores RegexOptions.Multiline. Should it respect RegexOptions.AnyNewLine, ie

flags    |    \Z is treated as         
------------- | ------------- 
`RegexOptions.AnyNewLine` | `(?=\r\n\z\|\r\z\|\n\z\|\z)` 
any case without above flag  |   `(?=\n\z\|\z)`

2019-10-07 01:58 UTC, jzabroski commented
Dan,

The intent of AnyNewLine is to allow engineers a succinct, portable way to match Unix or Windows style line endings.

Your recommendation seems to be in line with the intent, and am thankful for your watchful eye and feedback.

Is it too late to revise #28410 to include your addition? I still want to champion this as overall API improvement and see your remarks as further improvement.

That said, what becomes the specification of \Z anchor?

I think I should write up in plain English how this will end up appearing on https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference - I hate judging whether a specification change makes sense in a PR.

I feel we can all agree the \n in the current doc isn't Linux friendly or portable. The question is how to make the effects of AnyNewLine intuitive and also easy to read.

I'll try to summarize this tomorrow evening EST time.

2019-10-07 17:12 UTC, jzabroski requested changes
@shishirchawla Separate from @danmosemsft comments: It looks like you changed the specification to match old Mac style line endings, too.  This explodes the number of test cases you have to write, since every `|` in the Regex increases the base number that is being raised to the power of 2.  It also reduces performance.  Am I missing discussion somewhere about adding support for that?  I re-read through all the comments sans watching the [API Review video](https://www.youtube.com/watch?v=ZHKLi8qWTCs&t=0h0m0s), which I will do tonight when I have access to audio (machine locked down at work / no speakers), and I don't see any discussion of supporting Mac-style.

Finally, I see what you did that resulted in Dan's comments: You added AnyEndZ.  This is probably a good improvement but should be discussed outside the PR - looking at this from the level of code is a distraction - I will update the original post in #28410 with these notes.

Please also make sure you cover the test given by @svick as this was one test that tripped up an API Reviewer.  https://github.com/dotnet/corefx/issues/28410#issuecomment-392884975

2019-10-07 19:27 UTC, danmosemsft commented
@jzabroski thanks for updating the original proposal. If my two tables above correctly reflect the desired outcome -- perhaps you could include those as well? It would have made it clearer to me, than trying to parse from the text description.

Wrt process, we do need an ack from at least @terrajobst to deviate from what was approved (although as I say, it wasn't 100% clear to me what that was)

2019-10-07 19:47 UTC, jzabroski commented
@danmosemsft I agree with you.  With due respect, I didn't want to just copy the table you gave because I wanted to verify it myself and independently construct it to make sure you didn't introduce a bug.  That is also what I meant in the OP about looking at the documentation and making sure we have the user stories right from a docs perspective, and that it'll be clear to users how this works.  In the OP, I introduced today the phrase "Anchor Modifier" which to my knowledge isn't used anywhere in the docs previously, despite MultiLine option being an "Anchor Modifier" in that... it modifies the meaning of the anchor.

Hope that's fair.  Here is the table I have in mind to fill out:

| flags | $ is treated as | $ documentation |  \Z is treated as | \Z documentation | 
| ----- | --------------- | ------------------- | ----------------- | -------------------- |
| neither |  |  |  |  |
| `RegexOptions.Multiline` |  |  |  |  |
| `RegexOptions.Multiline \| RegexOptions.AnyNewLine` |  |  |  |  |
| `RegexOptions.AnyNewLine` |  |  |  |  |

This puts everything for the reviewer in one place, so they're not flipping back and forth trying to figure out if the spec is right, which I'm imaginging both you and I concentrated hard on recently 👍

2019-10-07 20:06 UTC, danmosemsft commented
@jzabroski that sounds even better. Yes don't rely on anything I wrote without verification 😄

2019-10-08 02:17 UTC, shishirchawla commented
Hi @jzabroski , I think I saw the following comment - https://github.com/dotnet/corefx/issues/28410#issuecomment-376611805, that mentions the most commonly used line endings ('\n', '\r\n', and '\r') and just went with the assumption that it will be a good idea to deal with all three cases. Please let me know if you’d like me to remove the '\r' option. 

Regarding the AnyEndZ option, I think it makes sense to have it in parallel with the "$" modifier as when the MultiLine option is not used, the logic basic defaults to "\Z" so to me it makes sense to alter the definition of "\Z" in the same PR.

I will go over the test case that you mentioned and make sure that everythings working as expected.

2019-10-08 14:48 UTC, jzabroski commented
Yes, but I think @terrajobst  needs to approve the AnyEndZ opcode and the right place to do that is in the issue, not the PR - this of this from the perspective of the Microsoft Docs team and their job to update documentation for the end-user developers who will use this API.  It's not clear from the Video Review of the API if Immo said something about this, and his notes didn't communicate such.

The main thing I got from watching the video review is it took people awhile to understand the summary table explaining the current problem and how AnyNewLine should solve it.

Separately, last night I read through about 70 pages of Jeffrey Freidl's Mastering Regular Expressions and his coverage of line anchors to take a step back and make sure I wasn't missing anything, and also thinking how to communicate this to end-user developers.  I'm not kidding when I say literally >10% of Jeffrey's book covers how to capture the end of a line correctly.  I documented some of that here: https://github.com/jzabroski/Home/blob/master/RegularExpressions/README.md

2019-10-19 17:53 UTC, danmosemsft commented
@terrajobst can you help unblock @shishirchawla here pls?

2019-11-05 01:29 UTC, danmosemsft commented
Per discussion in the issue, we do want `\Z` to be affected as well. @jzabroski I've filled in your table. Does this look correct to you?

| flags | $ is treated as | $ documentation |  \Z is treated as | \Z documentation | 
| ----- | --------------- | ------------------- | ----------------- | -------------------- |
| neither |  `(?=\n\z\|\z)`  | The match must occur at the end of the string or before `\n` at the end of the string. |  (Same as `$` with this option.)  |  (Same as `$` with this option.) |
| `RegexOptions.Multiline` | `(?=\n\|\n\z\|\z)` | The match must occur at the end of the string or before `\n` anywhere in the string. | `(?=\n\z\|\z)`  | The match must occur at the end of the string or before `\n` at the end of the string. |
| `RegexOptions.Multiline \| RegexOptions.AnyNewLine` | `(?=\r\n\|\r\|\n\|\r\n\z\|\r\z\|\n\z\|\z)` | The match must occur at the end of the string or before `\r\n`, `\n` or `\r` anywhere in the string.  | `(?=\r\n\z\|\r\z\|\n\z\|\z)` |  The match must occur at the end of the string or before `\r\n`, `\n` or `\r` at the end of the string. |
| `RegexOptions.AnyNewLine` | `(?=\r\n\z\|\r\z\|\n\z\|\z)`  | The match must occur at the end of the string or before `\r\n`, `\n` or `\r` at the end of the string. |  (Same as `$` with this option.) |  (Same as `$` with this option.) |

2019-11-05 02:21 UTC, jzabroski commented
Yes, that is fine.  It adds the slight mod of accepting old Mac OS style line endings, which I suppose is OK.  Otherwise, the table is perfect.  Thanks for doing that :)  Been feeling overwhelmed running two open source projects and doing my main job / running a business.  If you're ever in Boston, I owe you a beer 🥂

2019-11-05 03:39 UTC, danmosemsft commented
@shishirchawla if you haven't lost interest, which would be understandable, I think we have all we need to finish this PR. Mostly just clearer tests I guess.

2019-11-05 03:48 UTC, shishirchawla commented
Thanks @danmosemsft . I will get started on this soon.

2019-11-06 21:09 UTC, maryamariyan commented
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your corefx repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/corefx <path to the patch created in step 1>`

2019-11-08 18:16 UTC, maryamariyan commented
Hey @shishirchawla don't forget to also click on the link posted by dnfclas bot here: https://github.com/dotnet/corefx/pull/41195#issuecomment-532997657
to sign contributor license agreement. Needed before we can merge.

2019-11-11 06:06 UTC, shishirchawla commented
Hi @danmosemsft /@jzabroski , I have added the missing test case and the required modifications for it. Please let me know if youd like me to add some specific tests.

2019-11-11 14:02 UTC, jzabroski commented on src/System.Text.RegularExpressions/tests/Regex.Match.Tests.cs
> +            yield return new object[] { @".*$", "foo\r\nbar", RegexOptions.AnyNewLine | RegexOptions.Multiline, 0, 8, true, "foo" };
Thank you, @shishirchawla .  Looks good to me.

2019-11-11 18:55 UTC, maryamariyan commented
@shishirchawla there's some errors showing up on the CI that need fixing. Please refer to: https://github.com/dotnet/corefx/pull/41195/checks?check_run_id=297038224

2019-11-11 19:11 UTC, jzabroski commented
@danmosemsft I added your wonderful table to the top of the original issue https://github.com/dotnet/corefx/issues/28410 - thanks again!

2019-11-14 06:19 UTC, shishirchawla commented
Hey @maryamariyan, I see there are some new compiler errors. Will look at this soon. Thanks for letting know.

2019-12-02 19:43 UTC, maryamariyan commented
Thank you for your contribution. As announced in #27549 the dotnet/runtime repository will be used going forward for changes to this code base. Closing this PR as no more changes will be accepted into master for this repository. If you’d like to continue working on this change please move it to dotnet/runtime.

2019-12-02 19:43 UTC, closed without merging

2020-01-07 21:15 UTC, danmosemsft commented
@shishirchawla do you plan to move this PR to dotnet/runtime repo so we can get it finished? If not maybe someone else will volunteer.

2020-01-07 22:35 UTC, jzabroski commented
I would be willing to do it if @shishirchawla has lost interest, but I would like to see Shishir get the credit for the work. It's been on my mind.

2020-01-08 15:21 UTC, shishirchawla commented
Hi @danmosemsft @jzabroski, I just created a PR for this in the run time repo https://github.com/dotnet/runtime/pull/1449

2020-01-08 16:42 UTC, jzabroski commented
AWESOME!! Thank you so much!  If you're ever in Boston, 🍹 🍸 at the Mandarin Oriental, on me.

2020-04-06 17:21 UTC, danmosemsft commented
https://github.com/dotnet/runtime/issues/25598