[Backport][Pipelines] Noop Writes when Reader completed
dotnet/corefx pull request #42981
Opened 2020-09-08 21:15 UTC by BrennanConroy

Backport of https://github.com/dotnet/runtime/pull/41071

## Customer Impact
Customers shouldn't be able to see any differences as we want to keep existing code working without modifications.
This is fixing a Pipelines usage pattern that could result in large memory pressure or OOMs in the worst case.

## Regression
No.

## Testing
Yes? Tests were written and existing tests required no changes.

## Risk
Low, change was purposefully tailored to not break existing code

2020-09-08 22:02 UTC, davidfowl approved these changes

2020-09-10 16:59 UTC, BrennanConroy commented
@Anipik Could you take a look to make sure I added the change to the build correctly?

2020-09-14 21:38 UTC, Anipik commented on src/packages.builds
> +      <Project Include="$(MSBuildThisFileDirectory)System.IO.Pipelines\pkg\System.IO.Pipelines.pkgproj">
nit: indentation

2020-09-14 21:43 UTC, Anipik requested changes
You need to update the package version and assembly version here https://github.com/dotnet/corefx/blob/release/3.1/src/System.IO.Pipelines/Directory.Build.props#L4-L5

2020-09-14 22:13 UTC, BrennanConroy commented on src/System.IO.Pipelines/Directory.Build.props
> +    <PackageVersion>4.7.3</PackageVersion>
Don't understand these versions at all

2020-09-14 22:27 UTC, Anipik commented on src/System.IO.Pipelines/Directory.Build.props
> +    <PackageVersion>4.7.3</PackageVersion>
https://github.com/dotnet/corefx/blob/release/3.1/Documentation/project-docs/library-servicing.md
can give u more context.

2020-09-14 22:59 UTC, Anipik commented on pkg/Microsoft.Private.PackageBaseline/packageIndex.json
> +        "4.7.2"
nit: add "4.7.3"

2020-09-14 23:00 UTC, Anipik commented on pkg/Microsoft.Private.PackageBaseline/packageIndex.json
> +        "4.0.2.2": "4.7.2"
this should "4.7.3"

2020-09-14 23:00 UTC, Anipik approved these changes
left 2 comments

2020-09-18 21:37 UTC, Anipik commented
They have been approved offline

2020-09-18 21:37 UTC, merged