[WIP] Backport missing SslStream API to 2.1
dotnet/corefx pull request #42993
Opened 2020-09-23 14:32 UTC by CarnaViire

Add missing ReadAsync API to SslStream. This is a backport of #29658 to 2.1 (only SslStream part)

Fix dotnet/runtime#38185

2020-10-01 04:55 UTC, DavoudEshtehari commented
Good job @CarnaViire. This change is fixed our issue with net core 2.1.

2020-10-01 10:54 UTC, stephentoub approved these changes

2020-10-01 12:12 UTC, CarnaViire commented
@ericstj @Anipik could you please review the backport?

2020-10-01 16:12 UTC, wfurt approved these changes
LGTM. 
I'm not sure if we need any packaging changes.

2020-10-01 16:47 UTC, karelz commented
@danmosemsft this is ready for review in Tactics - will it pop up in queries, or should we send an email?

2020-10-01 16:51 UTC, ericstj requested changes
Can you double check that this actually updates the references and the SDK is prepared to ship those updated references?  Updating reference assemblies isn't something we typically do in servicing.  If I create a new netcoreapp2.1 project today I see it references C:\Users\erics\.nuget\packages\microsoft.netcore.app\2.1.0\ref\netcoreapp2.1\System.Runtime.dll.

2020-10-01 16:54 UTC, danmosemsft commented
If it's for regular 2.1/3.1 servicing, it will pop in tactics. For 5.0 stuff we're usually sending mail if there isn't a meeting right away.

2020-10-01 17:07 UTC, danmosemsft commented
Please add servicing-consider when @ericstj is signed off

2020-10-01 17:09 UTC, danmosemsft commented
BTW @ericstj in dotnet/runtime, do we have validation to prevent this category of error? or is that something we're tracking?

2020-10-01 18:56 UTC, ericstj commented
@danmosemsft part of the servicing process is to require testing final fixes in the shipping product rather than rely on unit testing.  It's aim is to catch this type of integration issue.  We do have some coverage of this just later in the process.

We typically don't service our references.  We cannot because folks address them by TFM and cannot "require" a servicing update when they use a TFM.  Whenever a reference assembly is changed in servicing we need to carefully scrutinize how that reaches a customer.  We typically disallow any change whatsoever (so we haven't had a need for validation).  We've actually never shipped a servicing event to references since the start of .NETCore, though ASP.NET has in 3.x.

This change in particular is "safe" since it's representing API that was already present at GA of 2.1, but the SDK's architecture in 2.1 didn't account for servicing of references.   We just need to understand up front what the intent is here and how folks are expected to consume this fix.  If it's important enough that everyone see this fix, then the SDK probably needs to do something.

The ref-pack design in 3.0 permitted more decoupling here.  In dotnet/runtime we actually did work to make sure we can more easily service our ref-packs (so this change would be supported).  We could add validation in servicing to ensure that any ref-pack change is compatible with the GA ref-pack.  This would catch things like API additions in servicing (which this is not trying to do).   I'll file an issue for that.

2020-10-01 20:00 UTC, danmosemsft commented
@ericstj I meant something different: we had public API on SslStream src that was not present in the ref. We have tooling to compare the two in builds - shouldn't it flag that some of the public API was not in the ref? I'm likely missing part of the picture.

2020-10-01 21:21 UTC, ericstj commented
We have https://github.com/dotnet/arcade/issues/2570 tracking improving APICompat's handling of overrides.  APICompat isn't always running between src and ref, often it runs between different versions of a library or different frameworks where we want to permit adding overrides, thus the current behavior.  I agree it can be improved.

2020-10-02 20:55 UTC, ericstj approved these changes
Per offline conversation with @dsplaisted, the SDK cannot support updating reference assemblies without also updating the value in the runtimeconfig.json, which would break applications.

As a result, we can ship this fix but it will not be automatic.  *Libraries* consuming the fix need to set `RuntimeFrameworkVersion` to `2.1.x` (where x is whatever release this ships in) in order to get this fix.  Those libraries can still be used on any version of 2.1.  *Applications* can set the same property, but need to be aware that doing so will limit them to only run on a shared framework of that version or later.  If they wish to run on older shared frameworks they would need to manually produce a runtimeconfig.json.

@CarnaViire you should include this as part of the release notes for this servicing release.

2020-10-08 20:39 UTC, CarnaViire commented
As per offline communication with SqlClient team,

We discovered that the SqlClient nuget package provides both 2.1 and 3.1 versions of the library. It means that for 3.1+ applications, 3.1 version will be resolved, not 2.1, so the repro with projects provided in the issue dotnet/runtime#38185 does not seem to represent SqlClient scenarios.

Given that there is no customer hitting it and given that it seems SqlClient users are not going to hit the problem on supported versions (2.1 or 3.1+), we decided that we should wait with servicing until we have real customer reports of hitting the problem.

2020-10-08 20:39 UTC, closed without merging